name: Auto Minify JS and CSS Files

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [ master ]
    paths: 
      - 'assets/**/*.js'
      - 'assets/**/*.css'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: echo-default-env-variables
        run: |
            echo "Environment variables"
            echo "Home: ${HOME}"
            echo "GITHUB_WORKFLOW: ${GITHUB_WORKFLOW}"
            echo "GITHUB_ACTIONS: ${GITHUB_ACTIONS}"
            echo "GITHUB_ACTOR: ${GITHUB_ACTOR}"
            echo "GITHUB_REPOSITORY: ${GITHUB_REPOSITORY}"
            echo "GITHUB_EVENT_NAME: ${GITHUB_EVENT_NAME}"
            echo "GITHUB_WORKSPACE: ${GITHUB_WORKSPACE}"
            echo "GITHUB_SHA: ${GITHUB_SHA}"
            echo "GITHUB_REF: ${GITHUB_REF}"
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
  
      - name: Auto Minify
        uses: Spreeuw/auto-minify@workspace-environment-variable
        with:
          directory: 'assets'

      - name: Auto committing minified files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Generate minified JS and CSS files"